BDS/BDS/Controllers/CommentController.cs
using BDS.Common;
using BDS.Data.Dto;
using BDS.Helper;
using BDS.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BDS.Controllers
{
    
    public class CommentController : Controller
    {
        private readonly IProjectService _projectService;
        private readonly IProvinceService _provinceService;
        private readonly IDistrictService _districtService;
        private readonly ICriteriaService _criteriaService;
        private readonly ICommentService _commentService;
       
        List<Comment> comments = new List<Comment>();

        public CommentController(IProjectService projectService, IProvinceService provinceService, IDistrictService district, ICriteriaService criteriaService, ICommentService commentService)
        {
            _projectService = projectService;
            _provinceService = provinceService;
            _districtService = district;
            _criteriaService = criteriaService;
            _commentService = commentService;
        }
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult CommentList(long id)
        {
            var comments = _commentService.GetListById(id);
            return PartialView(comments);
        }

        // GET: Comment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Comment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comment/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            Comment cm = new Comment();
            cm.Image = new List<Image>();

            if (Request.Files.AllKeys.Any())
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {                    
                    HttpPostedFileBase file = Request.Files[i];

                    if (file != null)
                    {
                        Image img = new Image();
                        img = ImageUpload.UploadFile(file, img, true);
                        cm.Image.Add(img);
                    }
                }
            }

            long projecid = long.Parse(Request.Form["ProjectID"].ToString());
            cm.ProjectID = projecid;
            cm.UserID = long.Parse(Request.Form["UserID"].ToString());
            cm.Content = Request.Form["Content"].ToString();
            cm.CreatedDate = DateTime.Now;
            cm.Active = true;

            _commentService.Add(cm);
            comments = _commentService.GetListById(projecid);

            return RedirectToAction("CommentList", new {id = projecid } );
        }

        // GET: Comment/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Comment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Comment/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Comment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BDS/BDS/Controllers/UserController.cs
using BDS.Common;
using BDS.Data.Dto;
using BDS.Service;
using BotDetect.Web.Mvc;
using Facebook;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BDS.Controllers
{
    
    public class UserController : Controller
    {
        private readonly IProjectService _projectService;
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;

        List<Province> data = new List<Province>();
        List<District> district = new List<District>();
        public UserController(IProjectService projectService, IUserService userService, IRoleService roleService)
        {
            _projectService = projectService;
            _userService = userService;
            _roleService = roleService;
        }

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }

        // GET: User
        [HttpGet]
        public ActionResult Register()
        {
            var project = _projectService.GetListTopHome();
            ViewBag.TopHome = project;
            return View();
        }

        public ActionResult Login(string returnUrl = null)
        {
            ViewBag.ReturnUrl = returnUrl;
            var project = _projectService.GetListTopHome();           
            ViewBag.TopHome = project;
            return View();
        }
        public ActionResult LoginFacebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });

            return Redirect(loginUrl.AbsoluteUri);
        }

        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });


            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
                // Get the user's information, like email, first name, middle name etc
                dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
                string email = me.email;
                string userName = me.email;
                string firstname = me.first_name;
                string middlename = me.middle_name;
                string lastname = me.last_name;

                var user = new User();
                user.Email = email;
                user.UserName = email;
                user.Active = true;
                user.Name = firstname + " " + middlename + " " + lastname;
                user.CreatedDate = DateTime.Now;
                user.Active = true;
                user.RoleID = "2";
                var resultInsert = _userService.InsertForFacebook(user);
                if (resultInsert > 0)
                {
                    int[] userRoles = user.RoleID.Split(',').Select(o => int.Parse(o)).ToArray();
                    var userSession = new UserLogin();
                    userSession.UserName = user.Name;
                    userSession.UserID = user.ID;
                    userSession.UserRole = _roleService.GetAll().Where(t => userRoles.Contains((int)t.ID)).Select(o => o.Name).ToArray();
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                }
            }
            return Redirect("/");
        }
        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return Redirect("/");
        }
        [HttpPost]
        public ActionResult Login(LoginModel model, string ReturnUrl)
        {
            if (ModelState.IsValid)
            {               
                var result = _userService.Login(model.UserName, Encryptor.MD5Hash(model.Password));
                if (result == 1)
                {
                    var user = _userService.GetById(model.UserName);
                    int[] userRoles = user.RoleID.Split(',').Select(o => int.Parse(o)).ToArray();
                    var userSession = new UserLogin();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.ID;
                    userSession.UserRole = _roleService.GetAll().Where(t => userRoles.Contains((int)t.ID)).Select(o => o.Name).ToArray();
                    Session.Add(CommonConstants.USER_SESSION, userSession);

                    if (string.IsNullOrEmpty(ReturnUrl))
                        return Redirect("/");
                    else
                        return Redirect(ReturnUrl);
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khoá.");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng.");
                }
                else
                {
                    ModelState.AddModelError("", "đăng nhập không đúng.");
                }
            }
            return View(model);
        }

        [HttpPost]
        [CaptchaValidation("CaptchaCode", "registerCapcha", "Mã xác nhận không đúng!")]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {               
                if (_userService.CheckUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }
                else if (_userService.CheckEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email đã tồn tại");
                }
                else
                {
                    var user = new User();
                    user.UserName = model.UserName;
                    user.Name = model.Name;
                    user.Password = Encryptor.MD5Hash(model.Password);
                    user.Phone = model.Phone;
                    user.Email = model.Email;
                    user.Address = model.Address;
                    user.CreatedDate = DateTime.Now;
                    user.RoleID = "2";
                    user.Active = true;

                    var result = _userService.Insert(user);
                    if (result == null)
                    {
                        ViewBag.Success = "Đăng ký thành công";
                        model = new RegisterModel();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công.");
                    }
                }
            }
            return View(model);
        }



    }
}

BDS/BDS/Views/Home/About.cshtml
@using BDS.Data.Dto;


@{
    ViewBag.Title = "Giới thiệu";
}

<style>
    .main-wthree {
        background: #3b8fc5;
        min-height: 400px;
    }

        .main-wthree h2 {
            font-size: 30px;
            color: #FFF;
            margin-bottom: 1em;
            letter-spacing: 3px;
            text-align: center;
        }

    .sin-w3-agile {
        padding: 2em 0 0;
        margin: 0 auto;
        width: 30%;
    }

    input, select {
        max-width: 100%;
    }
</style>



<div class="main-wthree">
    <div class="container">
        <div class="sin-w3-agile">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
</div>


<div class="list_du_an container">
    <div class="_title">
        <h2>Bất động sản mới nhất</h2>
    </div>

    <div class="row">
        @{
            var data = (List<Project>)ViewBag.TopHome;
        }
        @if (data != null && data.Any())
        {
            foreach (var item in data)
            {
                Html.RenderPartial("/Views/Home/_DuAnPartial.cshtml", item, null);
            }
        }
        else
        {

        }

    </div>
</div><br>

BDS/BDS/Views/Home/Contact.cshtml
@using BDS.Data.Dto;


@{
    ViewBag.Title = "Hướng dẫn";
}

<style>
    .main-wthree {
        background: #3b8fc5;
        min-height: 400px;
    }

        .main-wthree h2 {
            font-size: 30px;
            color: #FFF;
            margin-bottom: 1em;
            letter-spacing: 3px;
            text-align: center;
        }

    .sin-w3-agile {
        padding: 2em 0 0;
        margin: 0 auto;
        width: 30%;
    }

    input, select {
        max-width: 100%;
    }
</style>

<div class="main-wthree">
    <div class="container">
        <div class="sin-w3-agile">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
</div>

<div class="list_du_an container">
    <div class="_title">
        <h2>Bất động sản mới nhất</h2>
    </div>

    <div class="row">
        @{
            var data = (List<Project>)ViewBag.TopHome;
        }
        @if (data != null && data.Any())
        {
            foreach (var item in data)
            {
                Html.RenderPartial("/Views/Home/_DuAnPartial.cshtml", item, null);
            }
        }
        else
        {

        }

    </div>
</div><br>

BDS/BDS/Views/Home/Detail.cshtml
<link href="~/Assets/client/css/detail.css" rel="stylesheet" />
@using BDS.Data.Dto;
@using BDS.Common;
@model Project

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css{
           @Styles.Render("~/Assets/client/flexslider/flexslider.css")
}

@{
    var session = (UserLogin)Session[CommonConstants.USER_SESSION];
}
@if (session != null)
{
    <input type="hidden" id="UserID" value="@session.UserID" />
}


<style>
    hr{    
    border-top: 1px solid black;
}
    div.container-fluid{
        background-color:#3b8fc5;
    }
</style>

<form action="/Home/List" method="post">
    @*@Html.Partial("_TimKiemPartial", (List<Criteria>)ViewBag.Criterias);*@
</form>
<!-- Phần chi tiết -->
<div class="container _main">
    <div class="_slide_image">
        <div class="flexslider">
            <ul class="slides">
                @foreach (var img in Model.Image)
                {
                    <li>
                        <img class="" src="@img.Url@img.Name"  height="200px"/>
                    </li>
                }
                                                
            </ul>
        </div>

    </div>
    <div class="_content_title">
        <div class="_image_tilte col-md-2">
            @if (Model.Image != null && Model.Image.Any())
            {               
                <img src="@Model.Image.ElementAt(0).Url@Model.Image.ElementAt(0).Name" alt="Fjords" class="img-responsive">                               
            }
           
        </div>
        <div class="_thong_tin col-md-10" style="margin-left: -35px">
            <div class="_tieu_de col-sm-12"><b>@Model.Name</b></div>
            <div class="_dia_chi col-sm-12">@Model.Address</div>
            <div class="_gia col-sm-12">$: @Model.Price @Model.UnitPrice</div>
            <div class="_dien_tich col-sm-12">S: @Model.Acreage m2</div>
        </div>
    </div>
    <div class="_tab_box">
        <div class="_tab_menu col-md-9">
            <ul class="nav nav-pills">
                <li class="active"><a data-toggle="pill" href="#binhluan">Bình luận</a></li>
                <li><a data-toggle="pill" href="#mota">Mô tả</a></li>
                <li><a data-toggle="pill" href="#hinhanh">Hình ảnh</a></li>
            </ul>
        </div>
        <div class="_like_save col-md-3">

        </div>
    </div>

    <div class="_content_detail">
        <div class="_detail_col_left">
            <div class="tab-content">
                <div id="binhluan" class="tab-pane fade in active">
                    <div class="list-comment">
                        @{Html.RenderAction("CommentList", "Comment", new { id = Model.ID });}
                    </div>                                      
                    <div class="form-group">
                        <div class="col-md-12">
                            <textarea class="form-control" rows="5" id="txtComment" placeholder="Nội dung bình luận"></textarea>
                        </div>
                        <div class="col-md-12" style="margin-top: 10px">
                            <div class="col-md-4">
                                <button type="button" id="btnBinhLuan" class="btn btn-default" style="float:right">Gửi bình luận</button>
                            </div>
                            <div class="col-md-8">
                                <input class="btn-primary btn" id="fileComment" type="file" name="files" value="" multiple="multiple" />    
                            </div>                            
                        </div>                          
                    </div>                                                                
                </div>
                <div id="mota" class="tab-pane fade">
                    <h3>Thông tin mô tả</h3>
                    @Html.Raw(Model.Description)                   
                </div>
                <div id="hinhanh" class="tab-pane fade">
                    @foreach (var img in Model.Image)
                    {                        
                        <div class="_item_image">
                            <img src="@img.Url@img.Name" class="myImg img-thumbnail" alt="Thanh Pho" width="300" height="200">
                        </div>
                    }                                                                               
                </div>
            </div>
        </div>
        <div class="_detail_col_right">
            <div class="_ban_do">
                <div id="googleMap" style="height:100%;width:100%;"></div>
                <!-- Add Google Maps -->                               
                <script>
                  function initMap() {
                      var uluru = { lat:@Model.Lat, lng:@Model.Long};
                    var map = new google.maps.Map(document.getElementById('googleMap'), {
                      zoom: 12,
                      center: uluru,
                      scrollwheel: true,
                      draggable: true,
                      mapTypeId: google.maps.MapTypeId.ROADMAP
                    });
                    var marker = new google.maps.Marker({
                      position: uluru,
                      map: map
                    });
                  }
                </script>
                <script async defer
                        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCq2vNKISjdL0GJcmj_0oVqKCBEmwoV_os&callback=initMap">
                </script>
            </div>
            <div class="_lien_he">
                <div class="panel panel-default">
                    <div class="panel-heading">Liên Hệ</div>
                    <div class="panel-body">
                        @Html.Raw(Model.Contact)
                    </div>
                </div>

            </div>
            
        </div>
    </div>



</div>

<!-- The Modal -->
<div id="myModal" class="modal">
    <img class="modal-content" id="img01">
    <div id="caption"></div>
</div>

<div class="container-fluid" style="background-color:white; padding-top:10px; padding-bottom:30px; margin-top:5px">
    <div class="list_du_an container">
        <div class="_title">
            <h2>Bất động sản tương tự</h2>
        </div>

        <div class="row">
            @{
                var data = (List<Project>)ViewBag.ListTuongTu;
            }
            @if (data != null && data.Any())
            {
                foreach (var item in data)
                {
                    Html.RenderPartial("_DuAnPartial", item, null);
                }
            }
            else
            {
                <h2 style="text-align: center"><i>Hiện tại chưa có bất động sản tương tự.</i></h2>
            }

        </div>
    </div>
</div>

@section scripts{


@Scripts.Render("~/Assets/client/flexslider/jquery.flexslider.js")
<script type="text/javascript">

    $(document).ready(function(){
      $('.flexslider').flexslider({
        animation: "slide",
        animationLoop: false,
        itemWidth: 300,
        itemMargin: 5,

      });


        // Get the modal
      var modal = document.getElementById('myModal');

        // Get the image and insert it inside the modal - use its "alt" text as a caption
      var img = document.getElementsByClassName("myImg");
      var modalImg = document.getElementById("img01");
      var captionText = document.getElementById("caption");
      $(".myImg" ).on( "click", function() {
          modal.style.display = "block";
          modalImg.src = this.src;
          captionText.innerHTML = this.alt;
      });


      modal.onclick = function() {
          modal.style.display = "none";
      }

    });

    $("#btnBinhLuan").on("click", function () {
        var url = window.location.pathname + "?projectId=" + @Model.ID;
        var sess = @Html.Raw(Json.Encode(session));
        if (sess != null) {
            var txtComment = $("#txtComment").val();
            var projectid = @Model.ID;
            var userid = $("#UserID").val();

            var files = document.getElementById("fileComment").files;
            var formData = new FormData();

            if(files != null)
            {
                for (i = 0; i < files.length; i++) {
                    formData.append(files[i].name, files[i]);
                    console.log(files[i]);
                }
            }

            formData.append('ProjectID', projectid);
            formData.append('Content', txtComment);
            formData.append('UserID', userid);

            InsertComment(formData, null);
        }
        else
        {
            redirect(url);
        }

    });

    function redirect(retrunUrl) {
        var url = '@Url.Action("Login", "User", new { returnUrl = "url" })';
        window.location.href = url.replace('url', retrunUrl);
    }

    function InsertComment(formData, control) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Create", "Comment")',
            data: formData,
            processData: false,
            contentType: false,
            success: function (data) {
                console.log(data);
                $(".list-comment").html(data);
                location.reload();
            },

            error: function (request, status, error) {
                console.log(request.responseText);
            }
        });
    }

</script>
}

BDS/BDS/Views/Home/List.cshtml
@using BDS.Data.Dto.Request;
@using BDS.Data.Dto.Response;
@using BDS.Data.Dto;

@model SearchResult<Project>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Assets/client/css/detail.css" rel="stylesheet" />
<link href="~/Assets/client/css/list.css" rel="stylesheet" />
<form action="/Home/List" method="post">
    @Html.Partial("_TimKiemPartial", (List<Criteria>)ViewBag.Criterias);   
</form>

<div class="_list_main">
    <div class="_list_tim_kiem scrollbar" id="style-5">
        
        @if (Model.Data != null && Model.Data.Any())
        {
            var i = 1;
            foreach (var item in Model.Data)
            {

                <div class="_item_list" id="div-@item.ID">
                    <div class="_image_tilte">
                        @if (item.Image != null && item.Image.Any())
                        {
                            <a href="@Url.Action("Detail", "Home", new { projectId = item.ID})">
                                <img src="@item.Image.ElementAt(0).Url@item.Image.ElementAt(0).Name" alt="Fjords" class="img-responsive">
                            </a>
                        }

                    </div>
                    <div class="_thong_tin">
                        <div class="_tieu_de col-sm-12"><a href="@Url.Action("Detail", "Home", new { projectId = item.ID})"><b>@i. @item.Name</b></a></div>
                        <div class="_dia_chi col-sm-12">@item.Address</div>
                        <div class="_gia col-sm-12">$: @item.Price @item.UnitPrice</div>
                        <div class="_dien_tich col-sm-12">S: @item.Acreage m2</div>
                    </div>
                    <div class="_luu">
                        <button type="submit" id="btn_tim_kiem" class="btn btn-default" style="float: right;">Lưu</button>
                    </div>
                </div>
                i++;
            }
        }
        else
        {
            <p>Không tìm thấy dữ liệu</p>
        }
        <div class="force-overflow"></div>
    </div>
    <div class="_list_ban_do">
        <div id="googleMap" style="height:100%;width:100%;"></div>
        <!-- Add Google Maps -->
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCq2vNKISjdL0GJcmj_0oVqKCBEmwoV_os">
        </script>
        @Scripts.Render("~/bundles/googlemap")
        <script>
            $(function () {
                $("#googleMap").googleMap({
                    zoom: 1, // Initial zoom level (optional)
                    coords: [48.895651, 2.290569], // Map center (optional)
                    type: "ROADMAP" // Map type (optional)
                });
                               
                var labelIndex = 0;
                @foreach (var item in Model.Data)
                {                   
                    <text>
                        var image = {
                            url: '/Images/sothutu.png',
                            // This marker is 20 pixels wide by 32 pixels high.
                            size: new google.maps.Size(42, 50),
                            // The origin for this image is (0, 0).
                            origin: new google.maps.Point((labelIndex++)*42, 0),
                            // The anchor for this image is the base of the flagpole at (0, 32).
                            anchor: new google.maps.Point(21, 42)
                        };

                        $("#googleMap").addMarker({
                            coords: [@item.Lat, @item.Long],
                            url: '#div-@item.ID', // Link to redirect onclick (optional)
                            id: '@item.ID', // Unique ID for your marker
                            icon: image,
                            title: "@item.Name",
                            text: "Giá: @item.Price @item.UnitPrice | Diện tích: @item.Acreage m2"                            
                        });               
                    </text>                    
                }

            })
        </script>

    </div>
</div>

@section scripts{
<script>
        $(document).ready(function () {           
            $('select').select2({
                theme: "bootstrap"
            });
                
            
        });
</script>
    }

BDS/BDS/Views/Home/_DuAnPartial.cshtml
@using BDS.Data.Dto;
@model Project

<div class="col-sm-4" style="margin-bottom: 10px;" id="div-@Model.ID">
    <div class="img">
        @if (Model.Image!=null && Model.Image.Any())
        {
            <a href="@Url.Action("Detail", "Home", new { projectId = Model.ID})">
                <img src="@Model.Image.ElementAt(0).Url@Model.Image.ElementAt(0).Name" alt="Fjords" class="img-responsive">
            </a>           
        }
        
        <div class="_tieu_de col-sm-12"><b>@Model.Name</b></div>
        <div class="_dia_chi col-sm-12">@Model.Address</div>
        <div class="_gia col-sm-6">$: @Model.Price @Model.UnitPrice</div>
        <div class="_dien_tich col-sm-6">S: @Model.Acreage m2</div>
    </div>
</div>

BDS/BDS/Views/Home/_DuAnTuongTuPartial.cshtml
@using BDS.Data.Dto;
@model Project


<div class="">
    <div class="img">
        @if (Model.Image != null && Model.Image.Any())
        {
            <a href="@Url.Action("Detail", "Home", new { projectId = Model.ID})">
                <img src="@Model.Image.ElementAt(0).Url@Model.Image.ElementAt(0).Name" alt="Fjords" class="img-responsive">
            </a>           
        }
        
        <div class="_tieu_de col-sm-12"><b>@Model.Name</b></div>
        <div class="_dia_chi col-sm-12">@Model.Address</div>
        <div class="_gia col-sm-6">$: @Model.Price @Model.UnitPrice</div>
        <div class="_dien_tich col-sm-6">S: @Model.Acreage m2</div>
    </div>
</div>

BDS/BDS/Views/Home/_TaiChinhPartial.cshtml
@using BDS.Data.Dto;
@using BDS.Data.Enum;
@using BDS.Helper;
@model List<Criteria>

<div class="panel-group" id="accordion4">
  <div class="panel panel-default">
      <a data-toggle="collapse" data-parent="#accordion4" href="#taichinh1">
          <div class="panel-heading">
              <h4 class="panel-title">
                  Tài chính
              </h4>
          </div>
      </a>
    <div id="taichinh1" class="panel-collapse collapse in">
      <div class="panel-body">
              @{
                  var list = Model.Where(t => t.Type == 1).ToList();
                  var index = 0;
              }
              @foreach (var item in list)
              {
                  index = (int)item.ID - 1;
                <div class="row">
                    <div class="col-md-7">
                        <div class="checkbox">
                            @if (!string.IsNullOrEmpty(item.Description))
                            {
                                <label class="_tooltip" data-toggle="tooltip" data-placement="top" title="@item.Description">
                                    @Html.CheckBox("search.Criterias[" + index + "].Selected")@item.Name
                                </label>
                                        <input type="hidden" name="search.Criterias[@index].ID" value="@item.ID" />
                            }
                            else
                            {
                                <label>
                                    @Html.CheckBox("search.Criterias[" + index + "].Selected")@item.Name
                                </label>
                            }
                            <input type="hidden" name="search.Criterias[@index].ID" value="@item.ID" />
                        </div>
                    </div>
                    <div class="col-md-2">
                        <label class="_tooltip" data-toggle="tooltip" data-placement="top" title="">
                            @Html.CheckBox("search.Criterias[" + index + "].Prerequisite") Tiên quyết
                        </label>
                    </div>
                    <div class="col-md-3 form-group">
                        @Html.DropDownList("search.Criterias[" + index + "].Importance", Importance.Start.ToSelectList(), new { @class = "form-control" })
                    </div>
                </div>
                  index = index + 1;
              }
          
      </div>
    </div>
  </div>
     
</div>