BDS/BDS/Areas/Admin/Controllers/CriteriaController.cs
using BDS.Data.Dto;
using BDS.Service;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BDS.Areas.Admin.Controllers
{
    public class CriteriaController : BaseController
    {
        private readonly IProjectService _projectService;
        private readonly IProvinceService _provinceService;
        private readonly IDistrictService _districtService;
        private readonly ICriteriaService _criteriaService;
       
       
        public CriteriaController(IProjectService projectService, IProvinceService provinceService, IDistrictService district, ICriteriaService criteriaService)
        {
            _projectService = projectService;
            _provinceService = provinceService;
            _districtService = district;
            _criteriaService = criteriaService;
        }
        // GET: Admin/Criteria
        public ActionResult Index()
        {            
            return View();
        }

        [HttpGet]
        public PartialViewResult CriteriaList(int page = 1)
        {
            var model = _criteriaService.GetList();
            model = model.ToPagedList(page, _pageSize);
           
            return PartialView(model);
        }

        // GET: Admin/Criteria/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Criteria/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Criteria/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Criteria/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Criteria/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Criteria/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Criteria/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BDS/BDS/Areas/Admin/Controllers/ProjectController.cs
using BDS.Data.Dto;
using BDS.Data.Dto.Request;
using BDS.Data.Dto.Response;
using BDS.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BDS.Helper;
using PagedList;
using StaticResource;

namespace BDS.Areas.Admin.Controllers
{
    public class ProjectController : BaseController
    {
        private readonly IProjectService _projectService;
        private readonly IProvinceService _provinceService;
        private readonly IDistrictService _districtService;
        private readonly ICriteriaService _criteriaService;
        private readonly ITypeProjectService _typeProjectService;

        List<Province> data = new List<Province>();
        List<District> district = new List<District>();

        public ProjectController(IProjectService projectService, 
            IProvinceService provinceService, 
            IDistrictService district, 
            ICriteriaService criteriaService,
            ITypeProjectService typeProjectService)
        {
            _projectService = projectService;
            _provinceService = provinceService;
            _districtService = district;
            _criteriaService = criteriaService;
            _typeProjectService = typeProjectService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult ProjectList(int page = 1)
        {
            var model = _projectService.GetList();
            model = model.ToPagedList(page, _pageSize);

            return PartialView(model);
        }

        // GET: Admin/Admin
        [HttpGet]        
        public ActionResult Create()
        {
            ViewBag.Criterias = _criteriaService.GetAll();

            var typeProject = _typeProjectService.GetAll();
            ViewBag.TypeProject = typeProject;

            data = _provinceService.GetAll();
            ViewBag.CbProvince = data;

            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Project project, SearchProject search, HttpPostedFileBase[] files)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    project.Image = new List<Image>();
                    project.DetailProject = new List<DetailProject>();
                    var listCriteria = _criteriaService.FilterList(search.Criterias.ToList());

                    foreach (var item in listCriteria.ToList())
                    {
                        DetailProject dp = new DetailProject();
                        dp.CriteriaID = (int)item.ID;
                        dp.Value = !string.IsNullOrEmpty(item.Value) ? int.Parse(item.Value) : 0;

                        project.DetailProject.Add(dp);
                    }

                    if (files != null)
                    {
                        /*Lopp for multiple files*/
                        foreach (HttpPostedFileBase file in files)
                        {
                            Image img = new Image();
                            img = ImageUpload.UploadFile(file, img);
                            project.Image.Add(img);
                        }
                    }

                    project.CreatedDate = DateTime.Now;
                    project.Active = true;

                    ServiceResult<Project> result = _projectService.Add(project);

                    ViewBag.Message = "Thêm dự án thành công!";


                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Thêm dự án không thành công!";
                }
                return Create();
            }
            else
            {
                ModelState.AddModelError(string.Empty, Resource.CannotInsertData);
                return Create();
            }                       
        }
       

        public ActionResult GetDistrictByID(string id)
        {
            try
            {
                district = _districtService.GetAllById(id);
            }
            catch (Exception ex)
            {
                //Log errror
            }
            return Json(district, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAddress(string provinceid, string districtid)
        {
            string address = "";
            try
            {
                District district = _districtService.GetById(districtid);
                Province province = _provinceService.GetById(provinceid);

                address = district.Name + "," + province.Name;
            }
            catch (Exception ex)
            {
                //Log errror
            }
            return Json(address, JsonRequestBehavior.AllowGet);
        }
    }
}

BDS/BDS/Controllers/UserController.cs
using BDS.Common;
using BDS.Data.Dto;
using BDS.Service;
using BotDetect.Web.Mvc;
using Facebook;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BDS.Controllers
{
    
    public class UserController : Controller
    {
        private readonly IProjectService _projectService;
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;

        List<Province> data = new List<Province>();
        List<District> district = new List<District>();
        public UserController(IProjectService projectService, IUserService userService, IRoleService roleService)
        {
            _projectService = projectService;
            _userService = userService;
            _roleService = roleService;
        }

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }

        // GET: User
        [HttpGet]
        public ActionResult Register()
        {
            var project = _projectService.GetListTopHome();
            ViewBag.TopHome = project;
            return View();
        }

        public ActionResult Login(string returnUrl = null)
        {
            ViewBag.ReturnUrl = returnUrl;
            var project = _projectService.GetListTopHome();           
            ViewBag.TopHome = project;
            return View();
        }
        public ActionResult LoginFacebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });

            return Redirect(loginUrl.AbsoluteUri);
        }

        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });


            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
                // Get the user's information, like email, first name, middle name etc
                dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
                string email = me.email;
                string userName = me.email;
                string firstname = me.first_name;
                string middlename = me.middle_name;
                string lastname = me.last_name;

                var user = new User();
                user.Email = email;
                user.UserName = email;
                user.Active = true;
                user.Name = firstname + " " + middlename + " " + lastname;
                user.CreatedDate = DateTime.Now;
                user.Active = true;
                user.RoleID = "2";
                var resultInsert = _userService.InsertForFacebook(user);
                if (resultInsert > 0)
                {
                    int[] userRoles = user.RoleID.Split(',').Select(o => int.Parse(o)).ToArray();
                    var userSession = new UserLogin();
                    userSession.UserName = user.Name;
                    userSession.UserID = user.ID;
                    userSession.UserRole = _roleService.GetAll().Where(t => userRoles.Contains((int)t.ID)).Select(o => o.Name).ToArray();
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                }
            }
            return Redirect("/");
        }
        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return Redirect("/");
        }
        [HttpPost]
        public ActionResult Login(LoginModel model, string ReturnUrl)
        {
            if (ModelState.IsValid)
            {               
                var result = _userService.Login(model.UserName, Encryptor.MD5Hash(model.Password));
                if (result == 1)
                {
                    var user = _userService.GetById(model.UserName);
                    int[] userRoles = user.RoleID.Split(',').Select(o => int.Parse(o)).ToArray();
                    var userSession = new UserLogin();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.ID;
                    userSession.UserRole = _roleService.GetAll().Where(t => userRoles.Contains((int)t.ID)).Select(o => o.Name).ToArray();
                    Session.Add(CommonConstants.USER_SESSION, userSession);

                    if (string.IsNullOrEmpty(ReturnUrl))
                        return Redirect("/");
                    else
                        return Redirect(ReturnUrl);
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khoá.");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng.");
                }
                else
                {
                    ModelState.AddModelError("", "đăng nhập không đúng.");
                }
            }
            return View(model);
        }

        [HttpPost]
        [CaptchaValidation("CaptchaCode", "registerCapcha", "Mã xác nhận không đúng!")]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {               
                if (_userService.CheckUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }
                else if (_userService.CheckEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email đã tồn tại");
                }
                else
                {
                    var user = new User();
                    user.UserName = model.UserName;
                    user.Name = model.Name;
                    user.Password = Encryptor.MD5Hash(model.Password);
                    user.Phone = model.Phone;
                    user.Email = model.Email;
                    user.Address = model.Address;
                    user.CreatedDate = DateTime.Now;
                    user.RoleID = "2";
                    user.Active = true;

                    var result = _userService.Insert(user);
                    if (result == null)
                    {
                        ViewBag.Success = "Đăng ký thành công";
                        model = new RegisterModel();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công.");
                    }
                }
            }
            return View(model);
        }



    }
}

BDS/BDS/Areas/Admin/Views/Shared/_Layout.cshtml
@using BDS.Common;

<!DOCTYPE HTML>
<html>
<head>
    <title>Admin - Bất Động Sản</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Pooled Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Bootstrap Core CSS -->
    <link href="~/Assets/admin/css/bootstrap.min.css" rel="stylesheet" type='text/css'/>
    <!-- Custom CSS -->
    <link href="~/Assets/admin/css/style.css" rel="stylesheet" type='text/css'/>
    <link href="~/Assets/admin/css/morris.css" rel="stylesheet" type='text/css'/>
    <!-- Graph CSS -->
    <link href="~/Assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- jQuery -->
    <script src="~/Assets/admin/js/jquery-2.1.4.min.js"></script>
    <!-- Table-->
    <link href="~/Assets/admin/css/table-style.css" rel="stylesheet" />
    <link href="~/Assets/admin/css/basictable.css" rel="stylesheet" />
    <script src="~/Assets/admin/js/jquery.basictable.min.js"></script>
    <!-- //jQuery -->
    <link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css' />
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- lined-icons -->
    <link href="~/Assets/admin/css/icon-font.min.css" rel="stylesheet" type='text/css'/>
    <!-- //lined-icons -->
    <!-- Admin CSS -->
    <link href="~/Assets/admin/css/admin.css" rel="stylesheet" />

    <link href="~/Assets/select2/select2.css" rel="stylesheet" />
    
</head>
<body>
    <div class="page-container">
        <!--/content-inner-->
        <div class="left-content">
            <div class="mother-grid-inner">
                <!--header start here-->
                <div class="header-main">
                    <div class="logo-w3-agile">
                        <h1><a href="index.html">Bất Động Sản</a></h1>
                    </div>
            
                    <div class="profile_details w3l">
                        <ul>
                            <li class="dropdown profile_details_drop">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <div class="profile_img">
                                        <span class="prfil-img"><img src="~/Assets/admin/images/in4.jpg" alt=""> </span>
                                        @{
                                            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
                                        }
                                        <div class="user-name">
                                            <p>@session.UserName</p>
                                            <span>Quản trị viên</span>
                                        </div>
                                        <i class="fa fa-angle-down"></i>
                                        <i class="fa fa-angle-up"></i>
                                        <div class="clearfix"></div>
                                    </div>
                                </a>
                                <ul class="dropdown-menu drp-mnu">
                                    <li> <a href="#"><i class="fa fa-cog"></i> Settings</a> </li>
                                    <li> <a href="#"><i class="fa fa-user"></i> Profile</a> </li>
                                    <li> <a href="@Url.Action("Logout","User")"><i class="fa fa-sign-out"></i> Logout</a> </li>
                                </ul>
                            </li>
                        </ul>
                    </div>

                    <div class="clearfix"> </div>
                </div>
                <!--heder end here-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a> <i class="fa fa-angle-right"></i></li>
                </ol>

                <div class="main_page">
                    @RenderBody()
                </div>

                <!-- script-for sticky-nav -->
                <script>
                    $(document).ready(function () {
                        var navoffeset = $(".header-main").offset().top;
                        $(window).scroll(function () {
                            var scrollpos = $(window).scrollTop();
                            if (scrollpos >= navoffeset) {
                                $(".header-main").addClass("fixed");
                            } else {
                                $(".header-main").removeClass("fixed");
                            }
                        });

                    });
                </script>
                <!-- /script-for sticky-nav -->
                <!--inner block start here-->
                <div class="inner-block">

                </div>
                <!--inner block end here-->
                <!--copy rights start here-->
                <div class="copyrights">
                    <p>© 2016 Admin. Bất động sản cho người có thu nhập trung bình thấp!</p>
                </div>
                <!--COPY rights end here-->
            </div>
        </div>
        <!--//content-inner-->
        <!--/sidebar-menu-->
        <div class="sidebar-menu">
            <header class="logo1">
                <a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span> </a>
            </header>
            <div style="border-top:1px ridge rgba(255, 255, 255, 0.15)"></div>
            <div class="menu">
                <ul id="menu">                    
                    <li id="menu-academico">
                        <a href="@Url.Action("Index","Project")"><i class="fa fa-home" aria-hidden="true"></i><span> Quản lý dự án</span> <span class="fa fa-angle-right" style="float: right"></span><div class="clearfix"></div></a>
                        <ul id="menu-academico-sub">
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index","Project")">Danh sách dự án</a></li>
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Create","Project")">Thêm dự án</a></li>                            
                        </ul>
                    </li>
                    <li id="menu-academico">
                        <a href="@Url.Action("Index","Criteria")"><i class="fa fa-search" aria-hidden="true"></i><span> Quản lý tiêu chí</span> <span class="fa fa-angle-right" style="float: right"></span><div class="clearfix"></div></a>
                        <ul id="menu-academico-sub">
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index","Criteria")">Danh sách tiêu chí</a></li>
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index","Criteria")">Thêm tiêu chí</a></li>
                        </ul>
                    </li>
                    <li id="menu-academico">
                        <a href="@Url.Action("Index","User")"><i class="fa fa-user-o" aria-hidden="true"></i><span> Quản lý user</span> <span class="fa fa-angle-right" style="float: right"></span><div class="clearfix"></div></a>
                        <ul id="menu-academico-sub">
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index","User")">Danh sách user</a></li>
                            <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index","User")">Thêm user</a></li>
                        </ul>
                    </li>
                                        
                </ul>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <script>
        var toggle = true;

        $(".sidebar-icon").click(function () {
            if (toggle) {
                $(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
                $("#menu span").css({ "position": "absolute" });
            }
            else {
                $(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
                setTimeout(function () {
                    $("#menu span").css({ "position": "relative" });
                }, 400);
            }

            toggle = !toggle;
        });
    </script>
    <!--js -->
    <script src="~/Assets/admin/js/jquery.nicescroll.js"></script>
    <script src="~/Assets/admin/js/scripts.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Assets/admin/js/bootstrap.min.js"></script>
    <!-- /Bootstrap Core JavaScript -->
    <script src="~/Assets/select2/select2.js"></script>
    <script src="~/Assets/select2/vi.js"></script>

    <script src="~/Assets/admin/plugins/ckeditor/ckeditor.js"></script>
  
   

    <script>
        $(document).ready(function () {            
            $('select').select2({
                theme: "bootstrap"
            });
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>